# ===============================
# Configuracion de aplicacion
# ===============================
server.port=8080
spring.application.name=carrito-service

# ===============================
# Configuracion de Base de Datos
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/carrito_db
spring.datasource.username=user_carritos
spring.datasource.password=pass_carritos
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
